### ISSUE TITLE
ModPostProcessor.cs "error CS0246: The type or namespace name 'IdUtility' could not be found"

### ISSUE THREAD

**Issue by HexagonMods** [iceflake/survivingtheaftermath#1]
Impossible to use the Package there is an error:

`Assets\Toolkit\Scripts\Editor\ModPostProcessor.cs(16,66): error CS0246: The type or namespace name 'IdUtility' could not be found (are you missing a using directive or an assembly reference?)`

_I use Unity 2018.4.10f1_

**Comment by t-ifs** [comment]
This should be fixed in one of the previous updates.
